### ISSUE TITLE
It is very hard to extract the key lines from the paper in fairseq

### ISSUE THREAD

**Issue by gaceladri** [microsoft/fnl_paper#1]
Hello,

I was looking to the Frobenius norm in transformers-pytorch. I am not very seasoned with fairseq, so it is very hard to extract the 2-3 key lines from the paper.

Do you mind to create a branch or something deleting all the not used fairseq or document the key changes with respect to the original fairseq library?

Thank you.

**Comment by mkhodak** [comment]
Hi, I've added the locations of the major code differences from the original repo at the bottom of the readme in https://github.com/microsoft/fnl_paper/blob/main/Transformer-PyTorch . Let me know if that helps.

**Comment by gaceladri** [comment]
It helped! Thanks for your efforts and for making the project open source!
