### ISSUE TITLE
How to run the transformer experiment on iwslt14 dataset?

### ISSUE THREAD

**Issue by Sherrylife** [microsoft/fnl_paper#4]
Hi, @mkhodak , I want to know how to run the transformer experiment. When I run the command `bash prepare-iwslt14.sh`, there is an error happened:  "Please set SCRIPTS variable correctly to point to Moses scripts.", can you help me how to fix it?

Besides, the URL "https://wit3.fbk.eu/archive/2014-01/texts/de/en/de-en.tgz" is 404 and data can not be successfully downloaded.

**Comment by mkhodak** [comment]
Hello, the code you're having difficulty with was copied directly from [another repo](https://github.com/StillKeepTry/Transformer-PyTorch); I made some modifications, but not to the data-loading scripts. They worked for me, but I am not sure how to debug them.

For the specific issues you're running into:
1. Have you cloned the Moses github repo (see the commented code at the top of the script)?
2. I'm not sure where to access this data, but you might try the links [here](https://wit3.fbk.eu/2014-01).

**Comment by Sherrylife** [comment]
I'm sorry for forgetting to reply you. I have already solved this problem.
